### ISSUE TITLE
Does not appear to do anything

### ISSUE THREAD

**Issue by epistax** [shadi-danhash/swipe_effect#1]
I am looking for a solution for full-screen swipe detection with an effect. The demo for this library looks pretty good, however it the callback and visual effect never seem to happen. I have a gesture detector with an onTap callback around a PlatformScaffold and other assorted widgets inside. I've tried using SwipeEffect as the outter-most widget. I've tried inside the GestureDetector. I've tried removing the GestureDetector. In all situations, I cannot get the SwipEffect callback to fire, and there are no visual effects.

Implementation brief:
`SwipeEffect(
      direction: direction,
      color: direction == TextDirection.rtl
          ? Colors.red.withAlpha(70)
          : Colors.green.withAlpha(70),
      verticalTolerance: 1.0,
      startDeltaPx: start,
      callbackDeltaRatio: callbackDelta,
      callback: () {
        print('face');
        setState(() {
          start += 10;
          callbackDelta += 0.1;
        });
      },
      child: GestureDetector(...`

I've tried taking the values from both examples. Target is Pixel 4, API 31.

**Comment by shadi-danhash** [comment]
Dear @epistax it seems that your code works fine, please consider trying a large `startDeltaPx` value, as it determines at which pixel the swipe effect will start.
Also please consider testing on actual device, since it might be hard to swipe on the emulator (especially if the emulator system listens to horizontal swipe)
```dart
Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return GestureDetector(
      onTap: () {
        print('user clicked somewhere');
      },
      child: SwipeEffect(
        callback: () {
          print('user swiped');
        },
        startDeltaPx: size.width * 0.2,
        direction: TextDirection.ltr,
        child: Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _incrementCounter,
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
```

**Comment by epistax** [comment]
> Dear @epistax it seems that your code works fine, please consider trying a large `startDeltaPx` value, as it determines at which pixel the swipe effect will start. Also please consider testing on actual device, since it might be hard to swipe on the emulator (especially if the emulator system listens to horizontal swipe)
>

Thank you! Yes a very, very large startDeltaPx will work. size.width * 0.6 to 0.8. However now that I see the behavior I don't think it will work for me. I am looking for multiple swipe directions and I don't want to tell users that they have to press on the right side to swipe left, or the left side to swipe right. I'll check around for other options.

Thanks again.
